package:
    name: blast
    version: 2.2.26

source:
    fn: ncbi-blast-2.2.26+-x64-linux.tar.gz # [linux]
    url: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.26/ncbi-blast-2.2.26+-x64-linux.tar.gz # [linux]
    md5: 1749451aedf7b7bab24f57e5f4a865e0 # [linux]
    fn: ncbi-blast-2.2.26+-universal-macosx.tar.gz # [osx]
    url: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.26/ncbi-blast-2.2.26+-universal-macosx.tar.gz # [osx]
    md5: c4548075cab4e7215fa9ee9415e9a15b # [osx]
    patches:
        - legacy_blast.pl.patch
        - update_blastdb.pl.patch

build:
  number: 0

requirements:
    run:
        - perl
        - libgcc    # [not osx]

test:
    commands:
        - blastdb_aliastool -version > /dev/null
        - blastdbcheck -version > /dev/null
        - blastdbcmd -version > /dev/null
        - blast_formatter -version > /dev/null
        - blastn -version > /dev/null
        - blastp -version > /dev/null
        - blastx -version > /dev/null
        - convert2blastmask -version > /dev/null
        - deltablast -version > /dev/null
        - dustmasker -version > /dev/null
        - legacy_blast.pl --version > /dev/null
        - makeblastdb -version > /dev/null
        - makembindex -version > /dev/null
        - makeprofiledb -version > /dev/null
        - psiblast -version > /dev/null
        - rpsblast -version > /dev/null
        - rpstblastn -version > /dev/null
        - segmasker -version > /dev/null
        - tblastn -version > /dev/null
        - tblastx -version > /dev/null
        - windowmasker -version > /dev/null
        - update_blastdb.pl --version > /dev/null


about:
    home: http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastDocs
    license: Public Domain
    summary: BLAST+ is a new suite of BLAST tools that utilizes the NCBI C++ Toolkit.
